services:
  tasks:
    build:
      context: .
      dockerfile: ./apps/tasks/Dockerfile
      target: development
    command: npm run start:dev tasks
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
